
database:
  path: "/some/path/databases"
  name: "database.sqlite"
  dump: "structure_dump.sql"
mount:
  point: "/mnt/nas"
  path: "my/path/to/data"
users:
  - alice
  - bob
  - charlie
settings:
  flags:
    - debug
    - verbose
#     tasks:
#      - name: gate
#        args:
#         env: uat
#         approver:
#             - prabakarkesavpalo