# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
           echo Hello, world!
  
  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up GitHub CLI
        uses: github/gh-cli@v2

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.SECRET_TOKEN }}" | gh auth login --with-token

      - name: Create environment and Set up environment protection rules
        run: |
          REPO_OWNER="prabakarkesavpalo"
          REPO_NAME="testgha"
          ENVIRONMENT_NAME="production"
          APPROVERS="prabakarkesavpalo"

          # Create or update environment
          gh api \
            -X PUT \
            repos/$REPO_OWNER/$REPO_NAME/environments/$ENVIRONMENT_NAME \
            -f wait_timer=0

          echo "Environment $ENVIRONMENT_NAME created"
          # Clear existing protection rules
          gh api \
            -X DELETE \
            repos/$REPO_OWNER/$REPO_NAME/environments/$ENVIRONMENT_NAME/protection_rules

          # Add protection rules with approvers
          for APPROVER in $APPROVERS; do
            gh api \
              -X POST \
              repos/$REPO_OWNER/$REPO_NAME/environments/$ENVIRONMENT_NAME/protection_rules \
              -f reviewers='[{"type":"User","username":"'$APPROVER'"}]'
          done
          echo "Approvers $APPROVERS added to environment $ENVIRONMENT_NAME"


  deploy:
    runs-on: ubuntu-latest
    needs: approval
    environment: 
      name: production
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Build Badge
        if: always()
        run: echo "Build badge"
