# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
   inputs:
    environment:
     description: choos env
     required: true
     type: choice 
     options:
       - uat
       - prod
     
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  

jobs:
  # This workflow contains a single job called "build"
  # build:

  #   runs-on: ubuntu-latest

  #   container:
  #     image: node:14
  #   steps:
  #         # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #         - uses: actions/checkout@v4

  #         - name: Run a one-line script
  #           run: |
  #             echo "Hello, world!"  > $GITHUB_WORKSPACE/hello.txt


  deploy:
    runs-on: ${{ github.event.inputs.environment == "prod" && 'ubuntu-latest' || 'windows-latest' }}
    #needs: [ build ]
    steps:
        - name: Check Ubuntu Version
          if: runner.os == 'Linux'
          run: |
            lsb_release -a
            cat /etc/os-release
        - name: Check Windows OS Name
          if: runner.os == 'Windows'
          shell: pwsh 
          run: |
             $osInfo = Get-CimInstance -ClassName Win32_OperatingSystem
             $osName = $osInfo.Caption
             echo "Windows OS Name: $osName"

 

      # - name: Run a multi-line script
      #   run: |
      #      echo $tmp
