
name: Manual workflow call

on:
    workflow_call:
        inputs:
            name:
                type: string
                description: 'Name of the person'
                required: true
                default: 'John Doe'

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
