name: Main Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    uses: ./.github/workflows/reusable.yml
    with:
      environment: 'UAT'
      skip_sit: true
