name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Preparation Setup
        run: echo "Running preparation steps"

  parallel-jobs:
    needs: preparation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ['build', 'unit-test', 'packaging', 'sca']
    steps:
      - uses: actions/checkout@v4
      - name: ${{ matrix.job }}
        run: echo "Running ${{ matrix.job }}"

  build-sca-sast:
    needs: parallel-jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST Analysis
        run: echo "Running SAST analysis"

  image-build:
    needs: build-sca-sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: echo "Building application image"

  deploy-sit:
    needs: image-build
    runs-on: ubuntu-latest
    if: false  # This stage will be skipped but visible
    steps:
      - name: Deploy to SIT
        run: echo "Deploying to SIT environment"

  e2e-test-sit:
    needs: deploy-sit
    runs-on: ubuntu-latest
    if: false  # This stage will be skipped but visible
    steps:
      - name: Run E2E Tests
        run: echo "Running E2E tests in SIT"

  deploy-uat:
    needs: image-build  # Changed dependency to image-build to skip SIT stages
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - name: Deploy to UAT
        run: echo "Deploying to UAT environment"