name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Preparation Setup
        run: echo "Running preparation steps"

  parallel-jobs:
    needs: preparation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ['build', 'unit-test', 'packaging', 'sca']
    steps:
      - uses: actions/checkout@v4
      - name: ${{ matrix.job }}
        run: echo "Running ${{ matrix.job }}"

  build-sca-sast:
    needs: parallel-jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST Analysis
        run: echo "Running SAST analysis"

  image-build:
    needs: build-sca-sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: echo "Building application image"

  deploy-sit:
    needs: image-build
    runs-on: ubuntu-latest
    environment: SIT
    steps:
      - name: Deploy to SIT
        run: echo "Deploying to SIT environment"

  e2e-test-sit:
    needs: deploy-sit
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E Tests
        run: echo "Running E2E tests in SIT"

  deploy-uat:
    needs: e2e-test-sit
    runs-on: ubuntu-latest
    environment:
      name: UAT
      # Optional: Add URL if you want to link to your deployment
      # url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to UAT
        run: |
          echo "Deploying to UAT environment"
          # Add your UAT deployment steps here
