name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      sast_analysis_message: "Running SAST analysis"
      build_message: "Building application image"
      deploy_sit_message: "Deploying to SIT environment"
      deploy_uat_message: "Deploying to UAT environment"