name: Reusable Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      skip_sit:
        required: false
        type: boolean
        default: false

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Preparation Setup
        run: echo "Running preparation steps"

  parallel-stages:
    needs: preparation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ['build', 'unit-test', 'packaging', 'sca']
    steps:
      - uses: actions/checkout@v4
      - name: ${{ matrix.job }}
        run: echo "Running ${{ matrix.job }}"

  sast:
    needs: parallel-stages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST Analysis
        run: echo "Running SAST analysis"

  image-build:
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: echo "Building application image"

  deploy-sit:
    needs: image-build
    runs-on: ubuntu-latest
    if: inputs.skip_sit == false
    steps:
      - name: Deploy to SIT
        run: echo "Deploying to SIT environment"

  e2e-test-sit:
    needs: deploy-sit
    runs-on: ubuntu-latest
    if: inputs.skip_sit == false
    steps:
      - name: E2E Tests
        run: echo "Running E2E tests in SIT"

  deploy-uat:
    needs: [image-build, e2e-test-sit]
    if: always() && (needs.e2e-test-sit.result == 'success' || needs.e2e-test-sit.result == 'skipped')
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Deploy to UAT
        run: echo "Deploying to UAT environment"
