name: Reusable Pipeline

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      skip_sit:
        required: false
        type: boolean
        default: false
      prep_message:
        required: false
        type: string
        default: "Running preparation"
      build_message:
        required: false
        type: string
        default: "Running build"
      test_message:
        required: false
        type: string
        default: "Running tests"
      package_message:
        required: false
        type: string
        default: "Running packaging"
      sca_message:
        required: false
        type: string
        default: "Running SCA"
      sast_message:
        required: false
        type: string
        default: "Running SAST"
      image_message:
        required: false
        type: string
        default: "Building image"
      uat_message:
        required: false
        type: string
        default: "Deploying to UAT"
      prod_message:
        required: false
        type: string
        default: "Deploying to Production"

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Preparation Setup
        run: echo "${{ inputs.prep_message }}"

  parallel-stages:
    needs: preparation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ['build', 'unit-test', 'packaging', 'sca']
    steps:
      - uses: actions/checkout@v4
      - name: Build
        if: matrix.job == 'build'
        run: echo "${{ inputs.build_message }}"
      - name: Unit Test
        if: matrix.job == 'unit-test'
        run: echo "${{ inputs.test_message }}"
      - name: Packaging
        if: matrix.job == 'packaging'
        run: echo "${{ inputs.package_message }}"
      - name: SCA
        if: matrix.job == 'sca'
        run: echo "${{ inputs.sca_message }}"

  sast:
    needs: parallel-stages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST Analysis
        run: echo "${{ inputs.sast_message }}"

  image-build:
    needs: sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: echo "${{ inputs.image_message }}"

  deploy-uat:
    needs: image-build
    runs-on: ubuntu-latest
    environment:
      name: UAT
    steps:
      - name: Deploy to UAT
        run: echo "${{ inputs.uat_message }}"

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Deploy to Production
        run: echo "${{ inputs.prod_message }}"
